apiVersion: v1
kind: ConfigMap
metadata:
    name: stackdriver-exporter-config
    labels:
        app: {{ .Release.Name }}
        release: {{ .Release.Revision | quote }}
data:{{ range $key, $value := .Values.env }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}