kind: Service
apiVersion: v1
metadata:
  name: stackdriver-exporter-service
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Revision | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: stackdrivermetrics
      port: {{ .Values.service.httpPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}